#!/sbin/openrc-run
# Copyright 1999-2017 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

: ${logfile:="/var/log/influxdb/influxd.log"}
: ${config:="/etc/influxdb/influxdb.conf"}

name="InfluxDB daemon"
command="/usr/bin/influxd"
command_args="-config ${config}"
pidfile="/run/influxdb/influxdb.pid"
required_files="$config"

depend() {
	need net
	after bootmisc
}

start() {
	ebegin "Starting ${name}"
	start-stop-daemon --start -b \
		--user influxdb:influxdb \
		--make-pidfile \
		--pidfile ${pidfile} \
		--stdout ${logfile} \
		--stderr ${logfile} \
		--exec ${command} -- ${command_args}
	eend $?
}
