#!/sbin/openrc-run
# Copyright 1999-2017 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

: ${CONFIG:="/etc/influxdb/influxdb.conf"}
: ${LOGFILE:="/var/log/influxdb/influxd.log"}
: ${PIDFILE:="/run/influxdb.pid"}
: ${UG:="influxdb:influxdb"}

name="InfluxDB daemon"
command="/usr/bin/influxd"
command_args="-config ${CONFIG}"
command_background=yes
pidfile="${PIDFILE}"
start_stop_daemon_args="-u ${UG} \
	-1 ${LOGFILE} -2 ${LOGFILE}"

depend() {
	need net
	after bootmisc
}
