#!/sbin/openrc-run
# Copyright 1999-2017 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

: ${UG:="piknik:piknik"}
: ${CONFIG:="/etc/piknik.toml"}
: ${PIDFILE:="/run/piknik.pid"}

name="Piknik server"
command="/usr/bin/piknik"
command_args="-config ${CONFIG} -server"
command_background=yes
pidfile="${PIDFILE}"
start_stop_daemon_args="-u ${UG}"

depend() {
	need net
}
